# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fullName', models.CharField(blank=True, default='', max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'userDetails',
            },
        ),
    ]
