# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
