# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_auto_20180311_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
